# Generated by Django 2.0.2 on 2018-04-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsdatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bseatbooked',
            name='fare',
            field=models.IntegerField(default='0'),
        ),
    ]
