# Generated by Django 2.0.2 on 2018-04-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsdatabase', '0002_bseatbooked_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='bseatbooked',
            name='session',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
