# Generated by Django 2.0.2 on 2018-04-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsdatabase', '0004_auto_20180407_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='atime',
            field=models.CharField(default='0:0', max_length=15),
        ),
        migrations.AddField(
            model_name='flight',
            name='dtime',
            field=models.CharField(default='0:0', max_length=15),
        ),
    ]
