# Generated by Django 2.0.2 on 2018-04-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsdatabase', '0007_auto_20180407_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='bseatbooked',
            name='btime',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='bseatbooked',
            name='bdate',
            field=models.DateField(default='1999-2-12', verbose_name='date published'),
        ),
    ]
