# Generated by Django 2.0.2 on 2018-04-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsdatabase', '0009_auto_20180407_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bseatbooked',
            name='rtime',
        ),
        migrations.RemoveField(
            model_name='fseatbooked',
            name='rtime',
        ),
        migrations.AlterField(
            model_name='bseatbooked',
            name='rdate',
            field=models.DateTimeField(default='1999-1-12'),
        ),
        migrations.AlterField(
            model_name='fseatbooked',
            name='rdate',
            field=models.DateTimeField(default='1999-1-12'),
        ),
    ]
