# Generated by Django 2.0.2 on 2018-04-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsdatabase', '0010_auto_20180407_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='bseatbooked',
            name='rtime',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='fseatbooked',
            name='rtime',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='bseatbooked',
            name='rdate',
            field=models.DateField(default='1999-1-12'),
        ),
        migrations.AlterField(
            model_name='fseatbooked',
            name='rdate',
            field=models.DateField(default='1999-1-12'),
        ),
    ]
