# Generated by Django 2.0.2 on 2018-04-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmsdatabase', '0011_auto_20180407_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='hcountry',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='hstate',
        ),
    ]
