# Generated by Django 2.0.2 on 2018-04-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmsdatabase', '0012_auto_20180408_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='htype',
        ),
    ]
