# Generated by Django 2.0.2 on 2018-04-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsdatabase', '0013_remove_hotels_htype'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='add',
            field=models.CharField(default='abc', max_length=150),
        ),
    ]
