# Generated by Django 2.0.2 on 2018-04-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsdatabase', '0014_hotels_add'),
    ]

    operations = [
       
    
       
    ]
