# Generated by Django 2.0.2 on 2018-04-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsdatabase', '0015_auto_20180408_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hroomfare',
            old_name='hrfid',
            new_name='rfid',
        ),
        migrations.AddField(
            model_name='hroombooked',
            name='age',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='hroombooked',
            name='name',
            field=models.CharField(default='abc', max_length=20),
        ),
        migrations.AlterField(
            model_name='hroombooked',
            name='hrfid',
            field=models.IntegerField(primary_key=True),
        ),
    ]
