# Generated by Django 2.0.2 on 2018-04-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsdatabase', '0016_auto_20180408_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hroomfare',
            old_name='rfid',
            new_name='hrfid',
        ),
        migrations.RemoveField(
            model_name='hroombooked',
            name='hrfid',
        ),
        migrations.AddField(
            model_name='hroombooked',
            name='rdate',
            field=models.DateField(default='1999-2-2', verbose_name='Date published'),
        ),
        migrations.AddField(
            model_name='hroombooked',
            name='rtime',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
