# Generated by Django 2.0.2 on 2018-04-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsdatabase', '0017_auto_20180408_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='hroombooked',
            name='rno',
            field=models.IntegerField(default='0'),
        ),
    ]
