# Generated by Django 2.0.2 on 2018-04-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsdatabase', '0020_auto_20180408_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='hroombooked',
            name='fare',
            field=models.IntegerField(default='0'),
        ),
    ]
