# Generated by Django 2.0.2 on 2018-04-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmsdatabase', '0021_hroombooked_fare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hroomfare',
            name='hid',
        ),
        migrations.AddField(
            model_name='hotels',
            name='roomfare',
            field=models.IntegerField(default='0'),
        ),
        migrations.DeleteModel(
            name='HRoomFare',
        ),
    ]
